name: bcienv
channels:
  - conda-forge
dependencies:
  - python=3.9.2
  - python-dateutil
  - setuptools
  - pip:
    - alembic==1.4.1
    - cloudpickle==1.6.0
    - dask==2021.4.1
    - dask-ml
    - databricks-cli==0.14.3
    - decorator==4.4.2
    - distributed==2021.4.1
    - docker==5.0.0
    - entrypoints==0.3
    - featuretools==0.24.0
    - flask==1.1.2
    - fsspec==2021.4.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.14
    - greenlet==1.1.0
    - gunicorn==20.1.0
    - heapdict==1.0.1
    - hyperopt==0.2.5
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - locket==0.2.1
    - mako==1.1.4
    - markupsafe==1.1.1
    - mlflow==1.17.0
    - msgpack==1.0.2
    - networkx==2.5.1
    - nlp-primitives==1.1.0
    - nltk==3.6.2
    - partd==1.2.0
    - prometheus-client==0.10.1
    - prometheus-flask-exporter==0.18.2
    - protobuf==3.16.0
    - psutil==5.8.0
    - pyaml==20.4.0
    - python-editor==1.0.4
    - pyyaml==5.4.1
    - querystring-parser==1.2.4
    - regex==2021.4.4
    - scikit-learn
    - scikit-optimize==0.8.1
    - smmap==4.0.0
    - sortedcontainers==2.3.0
    - sqlalchemy==1.4.14
    - sqlparse==0.4.1
    - tabulate==0.8.9
    - tblib==1.7.0
    - toolz==0.11.1
    - tornado==6.1
    - websocket-client==0.59.0
    - werkzeug==1.0.1
    - xgboost==1.4.1
    - zict==2.0.0
    - python-dotenv
